README.md, src/main/java/io/codeka/gaia/bo/Settings.java, src/main/java/io/codeka/gaia/runner/StackRunner.java, src/main/java/io/codeka/gaia/runner/config/DockerConfig.java, src/test/java/io/codeka/gaia/bo/SettingsTest.java, src/test/java/io/codeka/gaia/runner/config/DockerConfigTest.java
=> :sparkles: : add docker runner configuration

src/main/resources/static/css/prism.css, src/main/resources/static/css/style.css, src/main/resources/templates/job.html, src/main/resources/templates/module.html, src/main/resources/templates/settings.html, src/main/resources/templates/stack.html
=> ✨ : add output block on stack view

src/main/resources/templates/stack.html
=> 💄 : remove backend and provider conf

src/main/java/io/codeka/gaia/Gaia.java, src/main/java/io/codeka/gaia/bo/Stack.java, src/main/resources/templates/stack.html, src/main/resources/templates/stacks.html
=> ✨ : add description to a stack

src/main/java/io/codeka/gaia/bo/StackState.java, src/main/java/io/codeka/gaia/controller/StackController.java, src/main/java/io/codeka/gaia/runner/StackCommandBuilder.java, src/main/java/io/codeka/gaia/runner/StackRunner.java, src/main/java/io/codeka/gaia/runner/config/DockerConfig.java, src/main/resources/templates/stack.html, src/main/resources/templates/stacks.html, src/test/java/io/codeka/gaia/runner/StackCommandBuilderTest.java
=> ✨ : add stop job

pom.xml, src/main/java/io/codeka/gaia/bo/mustache/TerraformScript.java, src/main/java/io/codeka/gaia/config/MustacheConfig.java, src/main/java/io/codeka/gaia/config/SecurityConfig.java, src/main/java/io/codeka/gaia/runner/StackCommandBuilder.java, src/main/resources/mustache/terraform.mustache, src/test/java/io/codeka/gaia/runner/StackCommandBuilderTest.java
=> recycle : add mustache template for terraform scripts

pom.xml, src/main/resources/templates/layout/header.html, src/main/resources/templates/stack.html
add a confirmation message before stopping a stack
Closes #31
=> ✨ : add confirm message before stopping a stack

.travis.yml, README.md, pom.xml, src/main/java/io/codeka/gaia/config/ActuatorSecurity.java, src/main/resources/application.properties, src/test/java/io/codeka/gaia/config/ActuatorSecurityTest.java
implements healthcheck using spring-boot actuator.
resolves #52
=> ✨ : healthcheck

src/main/java/io/codeka/gaia/bo/Job.java, src/main/java/io/codeka/gaia/bo/JobType.java, src/main/java/io/codeka/gaia/runner/StackRunner.java, src/main/resources/static/css/style.css, src/main/resources/templates/stack.html, src/test/java/io/codeka/gaia/runner/StackRunnerTest.java
=> ✨ : add type for job

pom.xml, src/main/java/io/codeka/gaia/config/SecurityConfig.java, src/main/resources/application.properties, src/test/java/io/codeka/gaia/config/SecurityConfigTest.java
=> 🔧 : configurable admin password

src/main/java/io/codeka/gaia/bo/Job.java, src/main/java/io/codeka/gaia/bo/TerraformModule.java, src/main/java/io/codeka/gaia/config/BeansConfig.java, src/main/java/io/codeka/gaia/controller/TerraformCLIController.java, src/main/java/io/codeka/gaia/repository/TerraformCLIRepository.java, src/main/java/io/codeka/gaia/runner/StackRunner.java, src/main/java/io/codeka/gaia/runner/config/DockerConfig.java, src/main/resources/application.properties, src/main/resources/static/css/style.css, src/main/resources/templates/job.html, src/main/resources/templates/layout/sidebar.html, src/main/resources/templates/module.html, src/main/resources/templates/modules.html, src/main/resources/templates/stack.html, src/test/java/io/codeka/gaia/controller/TerraformCLIControllerTest.java, src/test/java/io/codeka/gaia/repository/TerraformCLIRepositoryTest.java, src/test/java/io/codeka/gaia/runner/StackRunnerTest.java
=> 41 terraform version mgmt

src/main/java/io/codeka/gaia/bo/Settings.java, src/main/java/io/codeka/gaia/controller/SettingsController.java, src/main/java/io/codeka/gaia/repository/SettingsRepository.java, src/main/resources/application.properties, src/test/java/io/codeka/gaia/bo/SettingsTest.java, src/test/java/io/codeka/gaia/controller/SettingsControllerTest.java, src/test/java/io/codeka/gaia/repository/SettingsRepositoryIT.java, src/test/java/io/codeka/gaia/repository/SettingsRepositoryTest.java
=> 🔧 : make settings persistent

src/main/java/io/codeka/gaia/runner/StackRunner.java, src/test/java/io/codeka/gaia/runner/StackRunnerTest.java
=> 🚸 : use TF_IN_AUTOMATION env var

src/main/resources/static/css/style.css, src/main/resources/templates/empty_page.tpl, src/main/resources/templates/index.html, src/main/resources/templates/job.html, src/main/resources/templates/module.html, src/main/resources/templates/module_description.html, src/main/resources/templates/modules.html, src/main/resources/templates/new_stack.html, src/main/resources/templates/settings.html, src/main/resources/templates/stack.html, src/main/resources/templates/stacks.html, src/main/resources/templates/vue_templates/breadcrumb.vue
=> 💄 : better navigation

src/main/resources/static/css/style.css, src/main/resources/templates/job.html, src/main/resources/templates/vue_templates/console.vue
=> ✨ : add vue component to display logs

src/main/java/io/codeka/gaia/bo/Job.java, src/main/java/io/codeka/gaia/controller/StackController.java, src/main/java/io/codeka/gaia/runner/StackRunner.java, src/main/resources/templates/stack.html, src/test/java/io/codeka/gaia/bo/JobTest.java, src/test/java/io/codeka/gaia/repository/JobRepositoryTest.java, src/test/java/io/codeka/gaia/runner/StackRunnerTest.java
=> ✨ : running jobs should be visible in history

pom.xml, src/main/java/io/codeka/gaia/controller/ModulesMVCController.java, src/main/java/io/codeka/gaia/teams/bo/User.java, src/main/java/io/codeka/gaia/teams/controller/TeamsRestController.java, src/main/java/io/codeka/gaia/teams/controller/UsersMVCController.java, src/main/java/io/codeka/gaia/teams/controller/UsersRestController.java, src/main/resources/static/css/style.css, src/main/resources/templates/layout/header.html, src/main/resources/templates/layout/sidebar.html, src/main/resources/templates/module.html, src/main/resources/templates/modules.html, src/main/resources/templates/users.html, src/main/resources/templates/vue_templates/breadcrumb.vue, src/test/java/io/codeka/gaia/controller/ModulesMVCControllerTest.java, src/test/java/io/codeka/gaia/teams/controller/TeamsRestControllerIT.java, src/test/java/io/codeka/gaia/teams/controller/TeamsRestControllerTest.java, src/test/java/io/codeka/gaia/teams/controller/UsersRestControllerIT.java, src/test/java/io/codeka/gaia/teams/controller/UsersRestControllerTest.java
Add teams selection in module screen.
Add users mgmt screen.
=> ✨ : add team mgmt in ui

.travis.yml
Add discord webhook to be notified of travis-ci build status
=> 👷 : add discord webhook

pom.xml, src/main/java/io/codeka/gaia/bo/Stack.java, src/main/java/io/codeka/gaia/bo/TerraformModule.java, src/main/java/io/codeka/gaia/controller/StackRestController.java, src/main/java/io/codeka/gaia/service/StackCostCalculator.java, src/main/resources/static/css/style.css, src/main/resources/templates/job.html, src/main/resources/templates/module.html, src/main/resources/templates/module_description.html, src/main/resources/templates/modules.html, src/main/resources/templates/new_stack.html, src/main/resources/templates/stack.html, src/main/resources/templates/vue_templates/markdown.vue, src/main/resources/templates/vue_templates/readme.vue, src/test/java/io/codeka/gaia/controller/StackRestControllerTest.java, src/test/java/io/codeka/gaia/service/StackCostCalculatorTest.java
=> ✨ : cost of ownership

src/main/java/io/codeka/gaia/bo/Job.java, src/main/java/io/codeka/gaia/bo/Stack.java, src/main/java/io/codeka/gaia/controller/StackController.java, src/main/java/io/codeka/gaia/controller/StackRestController.java, src/main/java/io/codeka/gaia/repository/TerraformCLIRepository.java, src/main/resources/static/css/style.css, src/main/resources/templates/stack.html, src/main/resources/templates/vue_templates/user-badge.vue, src/test/java/io/codeka/gaia/bo/JobTest.java, src/test/java/io/codeka/gaia/controller/StackControllerTest.java, src/test/java/io/codeka/gaia/controller/StackRestControllerTest.java, src/test/java/io/codeka/gaia/repository/JobRepositoryIT.java, src/test/java/io/codeka/gaia/repository/TerraformCLIRepositoryTest.java, src/test/java/io/codeka/gaia/runner/StackRunnerTest.java, src/test/java/io/codeka/gaia/service/StackCostCalculatorTest.java
=> 🚸 log user actions

pom.xml
=> 👷 : corrects integration test inclusion

.travis.yml
automates the build of the docker image when a tag is present on branch `master`
resolves #97
=> 👷 : build docker images on tags

src/main/resources/templates/modules.html, src/main/resources/templates/stacks.html
corrects card layout & module card description
resolves #115 & #112
=> 🐛 : cards layout

pom.xml, src/main/java/io/codeka/gaia/config/ActuatorSecurity.java, src/main/java/io/codeka/gaia/dashboard/controller/DashboardControllerAdvice.java, src/main/resources/application.properties, src/main/resources/static/css/responsive.css, src/main/resources/static/css/style.css, src/main/resources/templates/layout/sidebar.html
=> ✨ : navbar footer

.dockerignore
un-ignore `.git` directory as build information plugins need it
=> :see_no_evil: : update dockerignore

src/main/java/io/codeka/gaia/runner/StackRunner.java, src/main/java/io/codeka/gaia/stacks/bo/Job.java, src/main/java/io/codeka/gaia/stacks/controller/JobRestController.java, src/main/java/io/codeka/gaia/stacks/repository/StepRepository.java, src/main/java/io/codeka/gaia/stacks/workflow/JobWorkflow.java, src/main/java/io/codeka/gaia/stacks/workflow/state/ApplyFailedState.java, src/main/java/io/codeka/gaia/stacks/workflow/state/ApplyFinishedState.java, src/main/java/io/codeka/gaia/stacks/workflow/state/ApplyStartedState.java, src/main/java/io/codeka/gaia/stacks/workflow/state/JobState.java, src/main/java/io/codeka/gaia/stacks/workflow/state/NotStartedState.java, src/main/java/io/codeka/gaia/stacks/workflow/state/PlanFailedState.java, src/main/java/io/codeka/gaia/stacks/workflow/state/PlanFinishedState.java, src/main/java/io/codeka/gaia/stacks/workflow/state/PlanStartedState.java, src/main/java/io/codeka/gaia/stacks/workflow/state/RetryableState.java, src/main/resources/templates/job.html, src/main/resources/templates/vue_templates/job/job-metadata.vue, src/test/java/io/codeka/gaia/runner/StackRunnerTest.java, src/test/java/io/codeka/gaia/stacks/bo/JobTest.java, src/test/java/io/codeka/gaia/stacks/controller/JobRestControllerTest.java, src/test/java/io/codeka/gaia/stacks/workflow/JobWorkflowTest.java, src/test/java/io/codeka/gaia/stacks/workflow/state/ApplyFailedStateTest.java, src/test/java/io/codeka/gaia/stacks/workflow/state/ApplyFinishedStateTest.java, src/test/java/io/codeka/gaia/stacks/workflow/state/ApplyStartedStateTest.java, src/test/java/io/codeka/gaia/stacks/workflow/state/NotStartedStateTest.java, src/test/java/io/codeka/gaia/stacks/workflow/state/PlanFailedStateTest.java, src/test/java/io/codeka/gaia/stacks/workflow/state/PlanFinishedStateTest.java, src/test/java/io/codeka/gaia/stacks/workflow/state/PlanStartedStateTest.java
=> ✨ : retry job

src/main/resources/templates/stack.html
=> :bug: : correct job numbering

src/main/java/io/codeka/gaia/dashboard/controller/IndexController.java, src/main/java/io/codeka/gaia/modules/bo/TerraformModule.java, src/main/java/io/codeka/gaia/modules/controller/ModuleRestController.java, src/main/java/io/codeka/gaia/modules/controller/ModulesMVCController.java, src/main/java/io/codeka/gaia/modules/repository/TerraformModuleRepository.java, src/main/java/io/codeka/gaia/stacks/repository/StackRepository.java, src/main/java/io/codeka/gaia/teams/controller/TeamsRestController.java, src/main/resources/templates/modules.html, src/test/java/io/codeka/gaia/dashboard/controller/IndexControllerTest.java, src/test/java/io/codeka/gaia/modules/bo/TerraformModuleTest.java, src/test/java/io/codeka/gaia/modules/controller/ModuleRestControllerIT.java, src/test/java/io/codeka/gaia/modules/controller/ModuleRestControllerTest.java, src/test/java/io/codeka/gaia/modules/controller/ModulesMVCControllerTest.java, src/test/java/io/codeka/gaia/modules/repository/TerraformModuleRepositoryIT.java, src/test/java/io/codeka/gaia/teams/controller/TeamsRestControllerIT.java
=> 🐛 : users should be able to edit their modules

.github/CODEOWNERS
see https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners
=> 👥️ : add CODEOWNERS

src/main/java/io/codeka/gaia/modules/bo/TerraformImage.kt, src/main/java/io/codeka/gaia/runner/StackCommandBuilder.java, src/main/java/io/codeka/gaia/runner/StackRunner.java, src/main/java/io/codeka/gaia/stacks/bo/Job.java, src/main/java/io/codeka/gaia/stacks/controller/JobRestController.java, src/main/resources/static/css/style.css, src/main/resources/templates/job.html, src/main/resources/templates/stack.html, src/main/resources/templates/vue_templates/components/job/job-history.vue, src/main/resources/templates/vue_templates/components/job/job-metadata.vue, src/test/java/io/codeka/gaia/modules/bo/TerraformImageTest.kt, src/test/java/io/codeka/gaia/modules/controller/ModuleRestControllerIT.java, src/test/java/io/codeka/gaia/runner/StackCommandBuilderTest.java, src/test/java/io/codeka/gaia/runner/StackRunnerTest.java, src/test/java/io/codeka/gaia/stacks/controller/JobRestControllerTest.java
- add the possibility to delete an old job
- job history has now its own vue component
- minor fixes
Resolves #121
=> ✨ job removal

src/main/client/app/pages/dashboard/dashboard-routes.js, src/main/client/app/pages/login/login-routes.js, src/main/client/app/pages/modules/modules-routes.js, src/main/client/app/pages/settings/settings-routes.js, src/main/client/app/pages/stacks/stacks-routes.js, src/main/client/app/pages/users/users-routes.js, src/main/client/app/router.js, src/main/client/app/shared/services/update-page-title-guard.js
update page title for each route using a route metadata
=> ✨ : update page title for each route

package-lock.json, package.json, src/main/client/app/pages/modules/modules.vue, src/main/client/app/pages/stacks/stack-creation.vue, src/main/client/app/pages/stacks/stacks-routes.js, src/main/java/io/codeka/gaia/teams/bo.kt, src/test/java/io/codeka/gaia/teams/controller/UsersRestControllerIT.java, src/test/resources/db/10_user.js
* fixes the "save and run" button on stack creation
* changes the route for stack-creation screen 
* removes the uuid dependency
* do not leak a user's oauth2 token through APIs
=> 🐛 : small fixes

README.md
this will allow correct rendering on docker hub
resolves #366
=> 📝 : use absolute paths for images

src/main/client/app/pages/stacks/job/job-metadata.vue, src/main/client/app/pages/stacks/stack-creation.vue, src/main/client/app/pages/stacks/stack-edition.vue, src/main/client/app/pages/stacks/stacks.vue, src/main/java/io/gaia_app/stacks/bo/Stack.java, src/main/java/io/gaia_app/stacks/controller/JobRestController.kt, src/main/java/io/gaia_app/stacks/controller/StackRestController.java, src/main/java/io/gaia_app/stacks/service/MandatoryStackVariablesValidator.kt, src/main/java/io/gaia_app/stacks/service/RegexStackVariablesValidator.kt, src/main/java/io/gaia_app/stacks/service/StackCostCalculator.java, src/test/java/io/gaia_app/stacks/controller/JobRestControllerTest.kt, src/test/java/io/gaia_app/stacks/controller/StackRestControllerIT.java, src/test/java/io/gaia_app/stacks/controller/StackRestControllerTest.java, src/test/java/io/gaia_app/stacks/service/MandatoryStackVariablesValidatorTest.java, src/test/java/io/gaia_app/stacks/service/RegexStackVariablesValidatorTest.java, src/test/java/io/gaia_app/stacks/service/StackCostCalculatorTest.java, src/test/resources/db/30_stack.js
Stack has now a direct link to Module, in the form of a `@DbRef`
Also, update the look of the stack cards :)
resolves #103
=> ♻ : update Stack to have a DbRef onto Module

package-lock.json, package.json
Bumping two dependencies that dependabot didn't manage to update
=> ⬆️ : bump @vue/cli-plugin-vuex & eslint

src/main/java/io/gaia_app/config/security/RunnerApiSecurityConfig.java, src/main/java/io/gaia_app/runner/RunnerController.java, src/main/java/io/gaia_app/runner/StackCommandBuilder.java, src/main/java/io/gaia_app/stacks/bo/Stack.java, src/main/java/io/gaia_app/stacks/controller/TerraformStateController.java, src/main/java/io/gaia_app/teams/controller/UserControllerAdvice.java, src/main/resources/mustache/terraform.mustache, src/test/java/io/gaia_app/config/security/RunnerApiSecurityConfigIT.java, src/test/java/io/gaia_app/runner/StackCommandBuilderTest.java, src/test/java/io/gaia_app/stacks/bo/StackTest.java
=> ✨ : use a tfvar file in the runner instead of sending variables as command line parameters

src/main/client/app/pages/stacks/stack-edition.vue, src/main/client/app/pages/stacks/stacks.vue, src/main/client/app/shared/config/fontawesome-config.js, src/main/java/io/gaia_app/stacks/bo/Stack.java, src/main/java/io/gaia_app/stacks/bo/StackState.java, src/main/java/io/gaia_app/stacks/controller/StackRestController.java, src/test/java/io/gaia_app/stacks/controller/StackRestControllerIT.java, src/test/java/io/gaia_app/stacks/controller/StackRestControllerTest.java, src/test/resources/db/30_stack.js
This PR implements stack archiving:
* archiving a stack from any state
* un-archiving a stack
* filter in the stack list
resolves #122
Note, this should be merged after #525, as it uses it as a git base.
screenshots :
=> ✨ : archive stacks

.github/workflows/visual-non-regression-tests.yml
we need  percy to run on master branch, to have a baseline to compare to other builds !
=> 👷 : add percy on baseline branch

src/main/client/app/pages/stacks/job/job-step.vue, src/main/client/app/shared/config/fontawesome-config.js, src/main/java/io/gaia_app/runner/RunnerCommandBuilder.java, src/main/java/io/gaia_app/runner/RunnerController.java, src/main/java/io/gaia_app/stacks/bo/Plan.kt, src/main/java/io/gaia_app/stacks/bo/Step.java, src/main/java/io/gaia_app/stacks/bo/mustache/TerraformScript.java, src/main/java/io/gaia_app/stacks/repository/PlanRepository.java, src/main/resources/mustache/terraform.mustache, src/test/java/io/gaia_app/e2e/CucumberContextConfiguration.java, src/test/java/io/gaia_app/registries/controller/GitlabRegistryControllerIT.kt, src/test/java/io/gaia_app/runner/RunnerCommandBuilderTest.java, src/test/java/io/gaia_app/runner/RunnerControllerIT.java, src/test/java/io/gaia_app/stacks/bo/PlanTest.kt, src/test/resources/db/50_step.js, src/test/resources/db/80_plan.js, src/test/resources/sample-plan.json
This PR provides basic plan analysis :
* uploading plan to gaia
* getting number of created/updated/deleted resources
* showing this information in the job screen
=> ✨ : basic plan analysis

src/main/java/io/gaia_app/stacks/bo/Job.java, src/main/java/io/gaia_app/stacks/controller/JobRestController.kt, src/main/java/io/gaia_app/stacks/repository/JobRepository.kt, src/main/java/io/gaia_app/stacks/service/StackCostCalculator.java, src/test/java/io/gaia_app/stacks/controller/JobRestControllerTest.kt, src/test/java/io/gaia_app/stacks/service/StackCostCalculatorTest.java, src/test/resources/db/40_job.js
Add the scheduled date to jobs (which may differ from start date).
This date is used to order the list of jobs in the stack page.
resolves #527
=> ✨ : add scheduled date to jobs

.github/pull_request_template.md, CONTRIBUTING.md
Add contribution guidelines:
* CONTRIBUTING.md
* Github pull request template
resolves #118
=> 📝 : add contribution guidelines

src/main/client/app/pages/stacks/stack-edition.vue
When a stack variable is changed, set the stack status to `TO_UPDATE` to allow the change to be applied.
* resolves #287
=> 🐛 : set the stack status to TO_UPDATE on variable change

package-lock.json, package.json
bump @vue/cli dependencies to 4.5.13
bump vue to 2.6.14
bump vue-router to 3.5.2
bump vuex to 3.6.2
bump fortawesome to 5.15.3
bump core-js to 3.15.1
bump jquery to 3.6.0
bump marked to 2.1.2
(Please add issues resolution information when needed)
=> ⬆ : update a lot of dependencies

src/main/client/app/pages/credentials/providers/credentials-azurerm.vue, src/main/java/io/gaia_app/credentials/Credentials.kt, src/main/java/io/gaia_app/vault/VaultCredentialsService.kt, src/test/java/io/gaia_app/credentials/CredentialsRestControllerIT.java, src/test/java/io/gaia_app/credentials/CredentialsTest.kt, src/test/java/io/gaia_app/vault/VaultCredentialsServiceTest.kt
Added ARM_SUBSCRIPTION_ID, ARM_TENANT_ID, ARM_ACCESS_KEY and ARM_ENVIRONMENT as part of the Azure Credentials details
resolves #667
(Add a description of your pull request & feature here.
pull requests without an adequate description will not be reviewed until one is added.)
* Documentation PR : (eg: gaia-app/docs#2)
(Please add issues resolution information when needed)
=> ✨: extends AzureRM Credentials

Dockerfile, pom.xml
Update Dockerfile build phase to use openjdk-16
Also updates Kotlin, as support of openjdk-16 was implemented in Kotlin 1.5
* replaces #610 
* replaces #605 
* replaces #657 
(Please add issues resolution information when needed)
=> ⬆️ : feature/docker openjdk 16

CHANGELOG.md, pom.xml
=> 🔖 : bump version to 2.2.0

.dockerignore, .github/workflows/test.yml, .github/workflows/visual-non-regression-tests.yml, Dockerfile, pom.xml
Upgrade Dockerfile and Github actions to Java 17.
(Please add issues resolution information when needed)
=> ⬆️ : upgrade to java 17

pom.xml
see https://www.eclemma.org/jacoco/trunk/doc/prepare-agent-mojo.html
(Add a description of your pull request & feature here.
pull requests without an adequate description will not be reviewed until one is added.)
N/A
=> 💚 : move argLine to maven property to fix jacoco

src/main/client/app/pages/stacks/stack-edition.vue
in case of the module changes, users should be able to manually update a
stack
(Add a description of your pull request & feature here.
pull requests without an adequate description will not be reviewed until one is added.)
N/A
=> ✨ : allow running stacks to be updated

CHANGELOG.md, pom.xml
=> 🔖 : bump to 2.4.0
